[tool.poetry]
name = "elastic"
version = "0.1.0"
description = ""
authors = ["Rodney Rodriguez"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
elasticsearch = "^8.15.0"
jinja2 = "^3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
